---
title: "Group Project Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(ggplot2)
library(igraph)
library(stringr)
library("readxl")
library(dplyr)


dt.books <- fread("books.csv")
dt.books <- data.frame(dt.books[,c("title","authors","categories","published_year","average_rating")])
save(dt.books,file = "books.RData")
```

```{r}
#DATA CLEANING

#Reduce number of categories -> assume top10 categories in terms of amount of books published
dt.books2 <- data.table(dt.books)
dt.books.categories <- dt.books2[,list(n_cat = .N), by=categories][order(-n_cat)][1:50]
dt.books.clean <- dt.books[dt.books$categories %in% dt.books.categories[,categories],]

#Normalize title and authors names
dt.books.clean[,"title"] = str_to_title(dt.books.clean[,"title"])
dt.books.clean[,"authors"] = str_to_title(dt.books.clean[,"authors"])

#Separate authors 1 by 1 -> at maximum there is a book with 13 authors
dt.books.clean['authors1'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 1))
dt.books.clean['authors2'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 2))
dt.books.clean['authors3'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 3))
dt.books.clean['authors4'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 4))
dt.books.clean['authors5'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 5))
dt.books.clean['authors6'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 6))
dt.books.clean['authors7'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 7))
dt.books.clean['authors8'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 8))
dt.books.clean['authors9'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 9))
dt.books.clean['authors10'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 10))
dt.books.clean['authors11'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 11))
dt.books.clean['authors12'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 12))
dt.books.clean['authors13'] = as.character(lapply(strsplit(as.character(dt.books.clean[,"authors"]), 
                             split=";"), "[", 13))

#Remove original authors column
dt.books.clean <- subset( dt.books.clean, select = -authors )

#Create data sets with different authors to joined them in only one column
authors1 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors1")])
colnames(authors1) <- c('title','categories','published_year','average_rating','authors')

authors2 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors2")])
colnames(authors2) <- c('title','categories','published_year','average_rating','authors')

authors3 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors3")])
colnames(authors3) <- c('title','categories','published_year','average_rating','authors')

authors4 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors4")])
colnames(authors4) <- c('title','categories','published_year','average_rating','authors')

authors5 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors5")])
colnames(authors5) <- c('title','categories','published_year','average_rating','authors')

authors6 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors6")])
colnames(authors6) <- c('title','categories','published_year','average_rating','authors')

authors7 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors7")])
colnames(authors7) <- c('title','categories','published_year','average_rating','authors')

authors8 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors8")])
colnames(authors8) <- c('title','categories','published_year','average_rating','authors')

authors9 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors9")])
colnames(authors9) <- c('title','categories','published_year','average_rating','authors')

authors10 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors10")])
colnames(authors10) <- c('title','categories','published_year','average_rating','authors')

authors11 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors11")])
colnames(authors11) <- c('title','categories','published_year','average_rating','authors')

authors12 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors12")])
colnames(authors12) <- c('title','categories','published_year','average_rating','authors')

authors13 <- data.frame(dt.books.clean
                       [,c("title","categories","published_year","average_rating","authors13")])
colnames(authors13) <- c('title','categories','published_year','average_rating','authors')

authors <- rbind(authors1, authors2, authors3, authors4,authors5,
                     authors6, authors7, authors8, authors9, authors10,
                     authors11, authors12, authors13,fill = TRUE)

#Omit NA values e Distinct
dt.books.clean <- na.omit(authors)
dt.books.clean <- distinct(dt.books.clean[,c(colnames(dt.books.clean))])

View(dt.books.clean)

#Deal with Special characters
#install.packages("writexl")
writexl::write_xlsx(dt.books.clean,"dt.books.clean.xlsx")
dt.books.clean <- read_excel("dt.books.clean.xlsx")

#FINAL CLEANED - USE THIS DATA SET
save(dt.books.clean,file = "booksclean.RData")
```

```{r}
#DESCRIPTIVE STATISTICS

#Number of books per $column
ggplot(dt.books.clean,aes(x=categories)) + geom_bar() + ggtitle('Books per Category')
ggplot(dt.books.clean,aes(x=published_year)) + geom_bar() + ggtitle('Books per Year published')
ggplot(dt.books.clean,aes(x=authors)) + geom_bar() +  ggtitle('Books per Author')
ggplot(dt.books.clean,aes(x=average_rating)) + geom_histogram() +  ggtitle('Books per Ranking')

#Number of books with x authors

#MISSING

#First Authors with more published books
dt.books.clean <- data.table(dt.books.clean)
dt.books.clean[,list(n_books = .N), by=authors1][order(-n_books)][1:10]

#First Authors with more ranking
dt.books.clean[,list(authors_ranking = mean(average_rating)), by=authors][order(-authors_ranking)][1:10]
```

```{r}
#GRAPHS
dup = dt.books[duplicated(dt.books$title),]
dup.unique = dup[!duplicated(dup$title),]

more.than.one.author <- data.table(dt.books[dt.books$title %in% dup.unique$title,])

more.than.one.author.N <- more.than.one.author[order(-avg_rating_individual),][1:100,]
more.than.one.author.N <- na.omit(more.than.one.author.N)

all.authors <- more.than.one.author.N[,list(name=unique(authors),type=TRUE)]
all.books <- more.than.one.author.N[,list(name=unique(title),type=FALSE)]
all.vertices <- rbind(all.authors, all.books)
all.vertices <- na.omit(all.vertices)

g <- graph.data.frame(more.than.one.author.N[,list(authors,title)],directed=FALSE, vertices=all.vertices)

g.author <- bipartite.projection(g)$proj2

plot(g.author)
```

```{r}
#Centralities
#Degree centrality main graph - interesting
V(g.author)$degree <- degree(g.author)

#Closeness centrality - nop
V(g.author)$closeness <- closeness(g.author)

#Betweenness centrality - nop
V(g.author)$betweenness <- betweenness(g.author)

#Eigenvector centrality
V(g.author)$evcent <- evcent(g.author)$vector 

#Centrality Dataframe used afterwards
centrality.df <- data.table(get.data.frame(g.author, "vertices"))
centrality.df
```

```{r}
#Cluster Coefficient
transitivity(g.author, type='average')
```

```{r}
dt.books <- dt.books.clean

dt.books$avg_rating_class <- with(dt.books, ifelse(average_rating >= 0 & average_rating < 0.5, "[0-0.5[", ifelse(average_rating >= 0.5 & average_rating < 1, "[0.5 -1[", ifelse(average_rating >= 1 & average_rating < 1.5, "[1-1.5[", ifelse(average_rating >= 1.5 & average_rating < 2, "[1.5-2[", ifelse(average_rating >= 2 & average_rating <= 2.5, "[2-2.5]", ifelse(average_rating >= 2.5 & average_rating <= 3, "[2.5-3[", ifelse(average_rating >= 3 & average_rating <= 3.5, "[3-3.5[", ifelse(average_rating >= 3.5 & average_rating <= 4,  "[3.5-4[", ifelse(average_rating >= 4 & average_rating <= 4.5,  "[4-4.5[", ifelse(average_rating >= 4.5 & average_rating <= 5,  "[4.5-5]", "NA")))))))))))

average.ratings <- vector()
for (author in dt.books$authors) {
  the_author <- dt.books[dt.books$authors %in% author, ]
  average_rating_author <- mean(the_author$average_rating)
  average.ratings <- c(average.ratings, average_rating_author)
}
dt.books$avg_rating_individual <- average.ratings

dt.books$avg_rating_individual_class <- with(dt.books, ifelse(avg_rating_individual >= 0 & avg_rating_individual < 0.5, "[0-0.5[", ifelse(avg_rating_individual >= 0.5 & avg_rating_individual < 1, "[0.5 -1[", ifelse(avg_rating_individual >= 1 & avg_rating_individual < 1.5, "[1-1.5[", ifelse(avg_rating_individual >= 1.5 & avg_rating_individual < 2, "[1.5-2[", ifelse(avg_rating_individual >= 2 & avg_rating_individual <= 2.5, "[2-2.5[", ifelse(avg_rating_individual >= 2.5 & avg_rating_individual <= 3, "[2.5-3[", ifelse(avg_rating_individual >= 3 & avg_rating_individual <= 3.5, "[3-3.5[", ifelse(avg_rating_individual >= 3.5 & avg_rating_individual <= 4,  "[3.5-4[", ifelse(avg_rating_individual >= 4 & avg_rating_individual <= 4.5,  "[4-4.5[", ifelse(avg_rating_individual >= 4.5 & avg_rating_individual <= 5,  "[4.5-5]", "NA")))))))))))

main.categories <- vector()
for (author in dt.books$authors) {
  the_author <- dt.books[dt.books$authors %in% author, ]
  main.category <- names(sort(table(the_author$categories), decreasing=TRUE)[1])
  main.categories <- c(main.categories, main.category)
}

dt.books <- na.omit(dt.books)

dt.books$main_category <- main.categories

n.books <- vector()
for (author in dt.books$authors) {
  the_author <- dt.books[dt.books$authors %in% author, ]
  #the.author.unique <- the_author[!duplicated(the_author$title), ]
  n.books.author <- nrow(the_author)
  n.books <- c(n.books, n.books.author)
}
dt.books$n_books <- n.books

dt.books$n_books_class <- with(dt.books, ifelse(n.books >= 0 & n.books < 2, "[0-2[", ifelse(n.books >= 2 & n.books < 5, "[2-5[", ifelse(n.books >= 5 & n.books < 10, "[5 -10[", ifelse(n.books >= 10 & n.books < 15, "[10-15[", ifelse(n.books >= 15 & n.books < 20, "[15-20[", ifelse(n.books >= 20 & n.books <= 25, "[20-25[", ifelse(n.books >= 25 & n.books <= 30, "[25-30[", ifelse(n.books >= 30 & n.books <= 35, "[30-35[", ifelse(n.books >= 35 & n.books <= 40, "[35-40[", ifelse(n.books >= 40 & n.books <= 45, "[40-45]", "NA")))))))))))

```

```{r}
dt.books.unique <- data.table(dt.books[!duplicated(dt.books$authors), ])
dt.books.unique <- data.table(dt.books.unique[!dt.books.unique[,n_books_class] %in% c("[0-2[")][1:50,])

View(all.vertices)


all.authors <- dt.books.unique[,list(name=unique(authors),type=TRUE)]
all.ranks <- dt.books.unique[,list(name=unique(avg_rating_individual_class),type=FALSE)]
all.vertices <- rbind(all.authors, all.ranks)

g2 <- graph.data.frame(dt.books.unique[,list(all.authors,all.ranks)],directed=FALSE, vertices=NULL)

g.authors1 <- bipartite.projection(g)$proj2

plot(g.authors1)

dt.books.unique.similar.rank <- dt.books.unique[dt.books.unique$avg_rating_individual_class == author_class & dt.books.unique$n_books_class == author_n_books_class, ]
dt.books.unique.similar.rank$main.author <- author
dt.books.unique.similar.rank <- dt.books.unique.similar.rank[,c("main.author", "authors")]
dt.books.unique.similar.rank <- dt.books.unique.similar.rank <- dt.books.unique.similar.rank[!duplicated(dt.books.unique.similar.rank$authors), ]
g.books.ranking <- graph.data.frame(dt.books.unique.similar.rank, directed=FALSE, vertices = NULL)
plot(g.books.ranking)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```